build:
  image:  index.qiniu.com/library/alpine:3.4
  commands:
  - GOOS=linux GOARCH=amd64 go build helloworld.go
index.qiniu.com/kci/plugin_docker:
    repo: hanchaojie/helloworld
    tag:  latest
    insecure: false
    storage_path: /cache/ihebe
    when:
      event: [push,pull_request,tag,deployment]
index.qiniu.com/kci/plugin_email:
  recipients:
    - 1252680267@qq.com
  when:
      event: [push,pull_request,tag,deployment]
      status: [failure,success]
