workspace:
    base:   /workspace
    path: /workspace/test
pipeline:
  clone:
    image:  index.qiniu.com/kci/plugin_git
    remote: git@github.com:ihebe/github_test.git
    path: /workspace/github_test
  build:
    image: index.qiniu.com/kci/golang:1.6
    commands:
    - pwd
    - ls /workspace
    - GOOS=linux GOARCH=amd64 go build go/helloworld.go
  index.qiniu.com/kci/plugin_docker:
      repo: hanchaojie/helloworld
      tag: latest
      file: Dockerfile
      when:
        event: [push,pull_request,tag,deployment]
  index.qiniu.com/kci/plugin_email:
    recipients:
      - 1252680267@qq.com
    when:
      event: [push,pull_request,tag,deployment]
      status: [failure,success]

