pipeline:
  build:
    image: index.qiniu.com/kci/golang:1.6
    commands:
    - GOOS=linux GOARCH=amd64 go build go/helloworld.go
  index.qiniu.com/kci/plugin_docker:
      repo: hanchaojie/helloworld
      tag: latest
      when:
        event: [push,pull_request,tag,deployment]
  index.qiniu.com/kci/plugin_email:
    recipients:
      - 1252680267@qq.com
    when:
      event: [push,pull_request,tag,deployment]
      status: [failure,success]

